import 'package:meat_dictionary/meat/model/meat_model.dart';

List<MeatModel> porkList = [
  MeatModel(
    name: '가브리살',
    type: 'pork',
    usage: ['구이'],
    description: '항정살만큼 부드럽고 쫄깃한 부위',
    texture: 4.0,
    savoryFlavor: 3.0,
    meatAroma: 2.0,
    price: 4.0,
    imgPath: 'assets/imgs/pork/가브리살.png',
  ),
  MeatModel(
    name: '목살',
    type: 'pork',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: 1.0,
    savoryFlavor: 3.0,
    meatAroma: 2.0,
    price: 2.0,
    imgPath: 'assets/imgs/pork/목살.png',
  ),
  MeatModel(
    name: '삼겹살',
    type: 'pork',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: 3.0,
    savoryFlavor: 2.0,
    meatAroma: 2.0,
    price: 2.0,
    imgPath: 'assets/imgs/pork/삼겹살.png',
  ),
  MeatModel(
    name: '안심',
    type: 'pork',
    usage: ['돈가스'],
    description: '부드럽고 담백한',
    texture: 3.0,
    savoryFlavor: 3.0,
    meatAroma: 2.0,
    price: 2.0,
    imgPath: 'assets/imgs/pork/안심.png',
  ),
  MeatModel(
    name: '등심',
    type: 'pork',
    usage: ['돈가스, 탕수육'],
    description: '이건 구이로 먹지 마세요!',
    texture: 4.0,
    savoryFlavor: 3.0,
    meatAroma: 2.0,
    price: 2.0,
    imgPath: 'assets/imgs/pork/등심.png',
  ),
];
