import 'package:meat_dictionary/meat/model/meat_model.dart';

List<MeatModel> porkList = [
  MeatModel(
    id: 1,
    name: '가브리살',
    type: 'pork',
    usage: ['구이'],
    description: '항정살만큼 부드럽고 쫄깃한 부위',
    texture: Texture.slightlyChewy,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 4,
    imgPath: 'assets/imgs/pork/가브리살.png',
  ),
  MeatModel(
    id: 2,
    name: '목살',
    type: 'pork',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: Texture.verySoft,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/pork/목살.png',
  ),
  MeatModel(
    id: 3,
    name: '삼겹살',
    type: 'pork',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: Texture.normal,
    savoryFlavor: SavoryFlavor.slightlyMild,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/pork/삼겹살.png',
  ),
  MeatModel(
    id: 4,
    name: '안심',
    type: 'pork',
    usage: ['돈가스'],
    description: '부드럽고 담백한',
    texture: Texture.normal,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/pork/안심.png',
  ),
  MeatModel(
    id: 5,
    name: '등심',
    type: 'pork',
    usage: ['돈가스', '탕수육'],
    description: '이건 구이로 먹지 마세요!',
    texture: Texture.slightlyChewy,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/pork/등심.png',
  ),
];

List<MeatModel> beefList = [
  MeatModel(
    id: 1,
    name: '아롱사태',
    type: 'beef',
    usage: ['수육'],
    description: '항정살만큼 부드럽고 쫄깃한 부위',
    texture: Texture.slightlyChewy,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 4,
    imgPath: 'assets/imgs/beef/아롱사태.png',
  ),
  MeatModel(
    id: 2,
    name: '부채살',
    type: 'beef',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: Texture.verySoft,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/beef/부채살.png',
  ),
  MeatModel(
    id: 3,
    name: '안창살',
    type: 'beef',
    usage: ['구이'],
    description: '잘 고르기 도전해보자!',
    texture: Texture.normal,
    savoryFlavor: SavoryFlavor.slightlyMild,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/beef/안창살.png',
  ),
  MeatModel(
    id: 4,
    name: '안심',
    type: 'beef',
    usage: ['스테이크'],
    description: '부드럽고 담백한',
    texture: Texture.normal,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/beef/안심.png',
  ),
  MeatModel(
    id: 5,
    name: '등심',
    type: 'beef',
    usage: ['스테이크', '구이'],
    description: '이건 구이로 먹지 마세요!',
    texture: Texture.slightlyChewy,
    savoryFlavor: SavoryFlavor.normal,
    meatAroma: MeatAroma.weak,
    price: 2,
    imgPath: 'assets/imgs/beef/등심.png',
  ),
];
